export const MOCK_MOVIES = [
  {
    id: 1,
    title: 'Galactic Odyssey',
    overview: 'A crew of astronauts embarks on a perilous journey beyond the known universe, encountering alien civilizations and cosmic phenomena that challenge the very fabric of reality.',
    poster_path: null,
    backdrop_path: null,
    vote_average: 8.4,
    release_date: '2024-03-15',
    genre_ids: [878, 12, 18],
    genres: [{ id: 878, name: 'Science Fiction' }, { id: 12, name: 'Adventure' }],
  },
  {
    id: 2,
    title: 'Shadow Protocol',
    overview: 'A rogue intelligence agent uncovers a global conspiracy that reaches the highest levels of government, forcing her to question everything she once believed.',
    poster_path: null,
    backdrop_path: null,
    vote_average: 7.9,
    release_date: '2024-01-20',
    genre_ids: [28, 53, 80],
    genres: [{ id: 28, name: 'Action' }, { id: 53, name: 'Thriller' }],
  },
  {
    id: 3,
    title: 'Ember Falls',
    overview: 'Two strangers meet at a remote mountain lodge during a blizzard. As secrets unravel, their lives become intertwined in ways neither could have anticipated.',
    poster_path: null,
    backdrop_path: null,
    vote_average: 7.2,
    release_date: '2024-02-14',
    genre_ids: [10749, 18],
    genres: [{ id: 10749, name: 'Romance' }, { id: 18, name: 'Drama' }],
  },
  {
    id: 4,
    title: 'Iron Vanguard',
    overview: 'The world\'s last line of defense assembles when a technological titan rises to enslave humanity. Heroes must unite across fractured nations to stand against the iron tide.',
    poster_path: null,
    backdrop_path: null,
    vote_average: 8.1,
    release_date: '2024-05-01',
    genre_ids: [28, 12, 878],
    genres: [{ id: 28, name: 'Action' }, { id: 878, name: 'Sci-Fi' }],
  },
  {
    id: 5,
    title: 'The Last Lighthouse',
    overview: 'An aging lighthouse keeper on a remote island discovers a mysterious vessel carrying a child with no memory. Their bond becomes the key to unlocking an ancient maritime secret.',
    poster_path: null,
    backdrop_path: null,
    vote_average: 7.6,
    release_date: '2024-04-10',
    genre_ids: [18, 9648],
    genres: [{ id: 18, name: 'Drama' }, { id: 9648, name: 'Mystery' }],
  },
  {
    id: 6,
    title: 'Neon District',
    overview: 'In a sprawling cyberpunk metropolis, a street-level hacker takes on a powerful megacorporation after her brother is framed for a crime he didn\'t commit.',
    poster_path: null,
    backdrop_path: null,
    vote_average: 8.0,
    release_date: '2024-06-22',
    genre_ids: [878, 28, 80],
    genres: [{ id: 878, name: 'Sci-Fi' }, { id: 28, name: 'Action' }],
  },
  {
    id: 7,
    title: 'Verdant Realm',
    overview: 'A botanist discovers a hidden ecosystem deep in the Amazon where plants have evolved consciousness. Her findings threaten powerful industrial interests.',
    poster_path: null,
    backdrop_path: null,
    vote_average: 7.4,
    release_date: '2024-03-30',
    genre_ids: [12, 18, 878],
    genres: [{ id: 12, name: 'Adventure' }, { id: 18, name: 'Drama' }],
  },
  {
    id: 8,
    title: 'Crimson Tide Rising',
    overview: 'A decorated naval commander must make an impossible choice when a submarine crew mutinies in the midst of a nuclear standoff.',
    poster_path: null,
    backdrop_path: null,
    vote_average: 8.3,
    release_date: '2024-07-04',
    genre_ids: [28, 53, 18],
    genres: [{ id: 28, name: 'Action' }, { id: 53, name: 'Thriller' }],
  },
  {
    id: 9,
    title: 'Whispers in the Dark',
    overview: 'A true crime podcaster investigates a series of disappearances in a sleepy coastal town, only to find the horrors are far closer to home than she imagined.',
    poster_path: null,
    backdrop_path: null,
    vote_average: 7.7,
    release_date: '2024-10-31',
    genre_ids: [27, 9648, 53],
    genres: [{ id: 27, name: 'Horror' }, { id: 9648, name: 'Mystery' }],
  },
  {
    id: 10,
    title: 'Heist at Dawn',
    overview: 'A master thief comes out of retirement for one final score — breaking into the most secure vault in history with a team of unlikely allies.',
    poster_path: null,
    backdrop_path: null,
    vote_average: 7.8,
    release_date: '2024-08-16',
    genre_ids: [28, 80, 35],
    genres: [{ id: 28, name: 'Action' }, { id: 80, name: 'Crime' }],
  },
  {
    id: 11,
    title: 'Echoes of Tomorrow',
    overview: 'A scientist discovers a way to communicate with parallel versions of herself across timelines, but changing the past comes with devastating consequences.',
    poster_path: null,
    backdrop_path: null,
    vote_average: 8.2,
    release_date: '2024-09-05',
    genre_ids: [878, 18, 9648],
    genres: [{ id: 878, name: 'Sci-Fi' }, { id: 18, name: 'Drama' }],
  },
  {
    id: 12,
    title: 'Desert Wolves',
    overview: 'A family of smugglers navigating the lawless badlands must choose between their lucrative trade and their conscience when they stumble upon a humanitarian crisis.',
    poster_path: null,
    backdrop_path: null,
    vote_average: 7.5,
    release_date: '2024-11-20',
    genre_ids: [37, 28, 18],
    genres: [{ id: 37, name: 'Western' }, { id: 28, name: 'Action' }],
  },
];

export const MOCK_SERIES = [
  {
    id: 201, type: 'series',
    title: 'Quantum Nexus',
    overview: 'A rogue physicist discovers that reality is being rewritten by an unseen force. As she digs deeper, she must navigate parallel timelines, government conspiracies, and the limits of human perception.',
    poster_path: null, backdrop_path: null,
    vote_average: 8.7,
    release_date: '2023-09-10',
    genres: [{ id: 878, name: 'Science Fiction' }, { id: 9648, name: 'Mystery' }],
    seasons: [
      {
        seasonNumber: 1,
        episodes: [
          { episodeNumber: 1, title: 'Awakening', videoUrl: null, duration: 52 },
          { episodeNumber: 2, title: 'The Signal', videoUrl: null, duration: 48 },
          { episodeNumber: 3, title: 'Fracture Point', videoUrl: null, duration: 55 },
          { episodeNumber: 4, title: 'Dark Meridian', videoUrl: null, duration: 51 },
        ],
      },
      {
        seasonNumber: 2,
        episodes: [
          { episodeNumber: 1, title: 'New Horizons', videoUrl: null, duration: 54 },
          { episodeNumber: 2, title: 'The Collapse', videoUrl: null, duration: 49 },
          { episodeNumber: 3, title: 'Void Walker', videoUrl: null, duration: 58 },
        ],
      },
    ],
  },
  {
    id: 202, type: 'series',
    title: 'Crimson House',
    overview: 'Three estranged siblings return to their ancestral estate after their mother\'s mysterious death, only to uncover dark secrets buried beneath generations of silence.',
    poster_path: null, backdrop_path: null,
    vote_average: 8.3,
    release_date: '2024-03-01',
    genres: [{ id: 18, name: 'Drama' }, { id: 9648, name: 'Mystery' }],
    seasons: [
      {
        seasonNumber: 1,
        episodes: [
          { episodeNumber: 1, title: 'The Arrival', videoUrl: null, duration: 45 },
          { episodeNumber: 2, title: 'Old Wounds', videoUrl: null, duration: 43 },
          { episodeNumber: 3, title: 'Buried Truth', videoUrl: null, duration: 47 },
          { episodeNumber: 4, title: 'The Letter', videoUrl: null, duration: 44 },
          { episodeNumber: 5, title: 'Fire Season', videoUrl: null, duration: 50 },
        ],
      },
    ],
  },
  {
    id: 203, type: 'series',
    title: 'Steel & Shadow',
    overview: 'In a post-collapse city where corporations rule with private armies, a disgraced enforcer turned vigilante fights for survival and justice from the gutter up.',
    poster_path: null, backdrop_path: null,
    vote_average: 8.0,
    release_date: '2024-06-15',
    genres: [{ id: 28, name: 'Action' }, { id: 878, name: 'Science Fiction' }],
    seasons: [
      {
        seasonNumber: 1,
        episodes: [
          { episodeNumber: 1, title: 'Ground Zero', videoUrl: null, duration: 56 },
          { episodeNumber: 2, title: 'Iron City', videoUrl: null, duration: 51 },
          { episodeNumber: 3, title: 'Blood Debt', videoUrl: null, duration: 53 },
        ],
      },
    ],
  },
];

export const MOCK_GENRES = [
  { id: 28, name: 'Action' },
  { id: 12, name: 'Adventure' },
  { id: 35, name: 'Comedy' },
  { id: 80, name: 'Crime' },
  { id: 18, name: 'Drama' },
  { id: 27, name: 'Horror' },
  { id: 9648, name: 'Mystery' },
  { id: 10749, name: 'Romance' },
  { id: 878, name: 'Science Fiction' },
  { id: 53, name: 'Thriller' },
  { id: 37, name: 'Western' },
];

export const PLACEHOLDER_COLORS = [
  'from-blue-900 to-indigo-900',
  'from-purple-900 to-pink-900',
  'from-green-900 to-teal-900',
  'from-red-900 to-orange-900',
  'from-yellow-900 to-amber-900',
  'from-cyan-900 to-blue-900',
  'from-rose-900 to-red-900',
  'from-violet-900 to-purple-900',
  'from-emerald-900 to-green-900',
  'from-sky-900 to-cyan-900',
  'from-fuchsia-900 to-violet-900',
  'from-orange-900 to-yellow-900',
];
